name: SayUI
version: 1.0.0
main: Rendii09\SayUI\Main
api: [3.0.0, 4.0.0]
author: Rendii09

commands:
  sui:
    description: "SayUI Commands"
    permission: sui.cmd
    usage: /sui
permissions:
  sui.cmd:
    default: op
    description: "SayUI Commands"